### ISSUE TITLE
#US-15 Como Scrum Team queremos que la aplicación web y la móvil usen la misma base de datos para unificar datos

### ISSUE THREAD

**Issue by iannv** [TEAM-SALUS/SALUS-web#17]
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33

**Comment by melita-7** [comment]
Se cambian tareas al Sprint 0. (por error se pusieron como sprint 1)

**Comment by SebaOlimaQ** [comment]
completado el diagrama de clases

**Comment by ElAlef** [comment]
completado #TK-53 Realizar el modelo lógico

**Comment by iannv** [comment]
Se completó el DER
