### ISSUE TITLE
#US-16 Como Scrum Team queremos rediseñar y organizar el proyecto.

### ISSUE THREAD

**Issue by iannv** [TEAM-SALUS/SALUS-web#18]
- [x] #24
- [x] #26
- [x] #25
- [x] #27
- [x] #28

**Comment by RosanaQ** [comment]
#tk59 Se trabaja en la tarea junto a  @melita-7

**Comment by melita-7** [comment]
Se cambia historia de usuario y tareas al Sprint-0. (por error se puso sprint 1)

**Comment by iannv** [comment]
Se completó el MAPA DEL SITIO

**Comment by melita-7** [comment]
Se trabajo en conjunto la Planilla- Desarrollo Agil- con la compañera @RosanaQ .

**Comment by JEOrellano** [comment]
#US-16 Cerrada con éxito
